from typing import TYPE_CHECKING

if TYPE_CHECKING:

    class Event:
        """
        Stub for RV's event class, just so we have some basic auto complete and type checking.
        Overkill but fun...
        """

        def activationTime(self) -> float: ...
        def buttons(self) -> int: ...
        def contentMimeType(self) -> str: ...
        def contentType(self) -> int: ...
        def contents(self) -> str: ...
        def contentsArray(self) -> list[str]: ...
        def dataContents(self) -> bytes: ...
        def domain(self) -> tuple[float, float]: ...
        def domainVerticalFlip(self) -> bool: ...
        def key(self) -> int: ...
        def modifiers(self) -> int: ...
        def name(self) -> str: ...
        def pointer(self) -> tuple[float, float]: ...
        def pressure(self) -> float: ...
        def reference(self) -> tuple[float, float]: ...
        def reject(self) -> None: ...
        def relativePointer(self) -> tuple[float, float]: ...
        def returnContents(self) -> str: ...
        def rotation(self) -> float: ...
        def sender(self) -> str: ...
        def setReturnContent(self, content: str) -> None: ...
        def subDomain(self) -> tuple[float, float]: ...
        def tangentialPressure(self) -> float: ...
        def timeStamp(self) -> float: ...
        def xTilt(self) -> int: ...
        def yTilt(self) -> int: ...
